---
apiVersion: v1
kind: Secret
metadata:
    name: bggapp-secret
    labels:
        name: bggapp-secret
type: Opaque
data: 
    BGG_DB_PASSWORD: Y2hhbmdlaXQ=
    
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: bggapp-cm
    labels:
        name: bggapp-cm
data:
    BGG_DB_USER: root
    BGG_DB_HOST: bggdb-svc.bggns
    