---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: bggapp-v1-hpa
    labels:
        name: bggapp-v1-hpa
spec:
    minReplicas: 1
    maxReplicas: 4
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: bggapp-v1-deployment
    metrics:
    - type: Resource
      resource:
        name: memory
        target:
            type: Utilization
            averageUtilization: 80
    - type: Resource
      resource:
        name: cpu
        target:
            type: Utilization
            averageUtilization: 90       
        
    