apiVersion: v1
kind: Service
metadata:
  name: wp-svc
  labels:
    name: wp-svc

spec:
  ports:
    - port: 80
  selector:
    name: wp-pod
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
  labels:
    name: wp-deployment
spec:
  selector:
    matchLabels:
      name: wp-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: wp-pod
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wp-container

        envFrom:
        - configMapRef:
            name: wpapp-cm
        envFrom:
        - secretRef:
            name: wpapp-secret        
        ports:
        - containerPort: 80
          name: wp-pod-port

