---
apiVersion: v1
kind: Secret
metadata:
    name: wpapp-secret
    labels:
        name: wpapp-secret
type: Opaque
data: 
    WORDPRESS_DB_PASSWORD: Y2hhbmdlaXQ=
    MYSQL_ROOT_PASSWORD: Y2hhbmdlaXQ=
    # Config for MySQL CLuster
    ROOT_PASSWORD: Y2hhbmdlaXQ=
    DATABASE: d29yZHByZXNzX2Ri
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: wpapp-cm
    labels:
        name: wpapp-cm
data:
    WORDPRESS_DB_USER: root
    WORDPRESS_DB_HOST: wpdb-mysql-mysql-master.svc.cluster.local
    #MYSQL_DATABASE: wordpress_db
    WORDPRESS_DB_NAME: wordpress_db
    